/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
Title: Stylized planet
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber'

export function Astronaut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/stylized_planet.glb') 
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
      if (animations.length > 0) {
        actions[animations[0].name]?.play();
      }
    }, [actions, animations]);

    const yPosition = useMotionValue(5)
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1.5);
  }, [ySpring]);
  useFrame(() => {
    group.current.position.y = ySpring.get();
  });

  return (
    <group ref={group} {...props} 
    dispose={null}
    rotation={[-Math.PI / 2, -0.2, 2.2]} 
          scale={props.scale || 1}
          position={props.position || [1.3, -1.5, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" 
        // rotation={[-1.54, -0.064, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Clouds_1">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Clouds}
                />
              </group>
              <group name="Planet_2">
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Planet}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/stylized_planet.glb')
